name: presentation
description: Presentation package
version: 1.0.0

environment:
  sdk: '>=2.16.1 <3.0.0'


dependencies:
  bloc: ^8.0.3

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  bloc_test: ^9.0.3
