name: data_source
description: Datasource package
version: 1.0.0
publish_to: none


environment:
  sdk: '>=2.16.1 <3.0.0'


dependencies:
  dio: ^4.0.4
  mockito: ^5.1.0
  infrastructure:
    path: ../infrastructure

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  freezed: ^1.1.1
  freezed_annotation: ^1.0.0
  build_runner: ^2.1.2
