// Mocks generated by Mockito 5.1.0 from annotations
// in domain/test/lib/src/use_cases/shorten_link_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:domain/src/entities/entities.dart' as _i2;
import 'package:domain/src/repositories/shortener/i_link_shortener_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeShortenedUrl_0 extends _i1.Fake implements _i2.ShortenedUrl {}

/// A class which mocks [ILinkShortenerRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockILinkShortenerRepository extends _i1.Mock
    implements _i3.ILinkShortenerRepository {
  MockILinkShortenerRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ShortenedUrl> shortenUrl(String? url) => (super.noSuchMethod(
          Invocation.method(#shortenUrl, [url]),
          returnValue: Future<_i2.ShortenedUrl>.value(_FakeShortenedUrl_0()))
      as _i4.Future<_i2.ShortenedUrl>);
}
